name: Sage Maker Custom Container
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      image_uri: ${{ steps.set-image-uri.outputs.IMAGE_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.ROLE_ARN }}

      - name: Debug IAM user
        run: aws sts get-caller-identity

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_NAME }}:latest"
          echo "Building Docker image: $IMAGE_URI"
          docker build -t $IMAGE_URI -f ML/src/Dockerfile .

          # Set environment variable for this workflow
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

          # Also set as step output to pass to job output
          echo "::set-output name=IMAGE_URI::$IMAGE_URI"

        id: set-image-uri

      - name: Push Docker image
        run: docker push $IMAGE_URI
