name: Sage Maker Custom Container
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

# For OCID authorization 
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.ROLE_ARN }}

      - name: Debug IAM user
        run: aws sts get-caller-identity

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_NAME }}:latest"
          echo "Building Docker image: $IMAGE_URI"
          docker build -t $IMAGE_URI -f ML/src/Dockerfile .

          # Set environment variable for this w
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name : Save the IMAGE_URI to JSON  
        run :
          echo "{\"image_uri\":\"$IMAGE_URI\"}" >> image.json
      - name : Save the file to an arttifact
        uses : actions/upload-artifact@v4
        with : 
          name : image_info.json
          path : image.json

      - name: Push Docker image
        run: docker push $IMAGE_URI
