name: SageMaker Deployment
on:
  workflow_run:
    workflows: ["Sage Maker Custom Container"]
    types:
      - completed

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MODEL_OUTPUT: ${{ secrets.MODEL_OUTPUT }}
  ROLE_ARN: ${{ secrets.ROLE_ARN }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  MODEL_NAME: ${{ secrets.MODEL_NAME }}
  SAGEMAKER_ENDPOINT: ${{ secrets.SAGEMAKER_ENDPOINT }}

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set IMAGE_URI from previous workflow
        run: |
          IMAGE_URI="${{ github.event.workflow_run.outputs.image_uri }}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install "sagemaker>=2.0.0,<3.0.0" dotenv boto3

      - name: Deploy model
        run: |
          python ML/src/deploy.py
